---
title: "Biplabendu Das"
---

I am a doctoral student in the parasitic behavioral manipulation lab based at the [Department of Biology](http://sciences.ucf.edu/biology/) at the University of Central Florida. More specifically, our lab focusses on the enigmatic "zombie ant" fungus (*Ophiocordyceps unilateralis*) that infects and manipulates the behavior of the Florida carpenter ants, *Camponotus floridanus*. 
My Ph.D. supervisor, [Dr. Charissa de Bekker](http://sciences.ucf.edu/biology/debekkerlab/), has been pioneering protocols for successfully culturing the fungus in the lab and performing infections that yield manipulations in laboratory conditions. Having gone through a few months of struggle, we have finally been able to obtain successful manipulations in *C. floridanus* ants. So, yay! 

If you aren't familiar with the "zombie ant" phenomenon, here is what happens. Fungal spores land on the ants' cuticle (exoskeleton) while they forage for food or other resources. Once the spore burrows through and infects the ant, the fungus gradually changes the behavior of its host. Personal observations indicate a phase of hyperactivity which is followed by a period of inactivity in the infected ants. However, the striking behavioral change occurs when the ant leaves the nest, climbs up the vegetation and latches on to a substrate with her mandibles. Being atrophied, the ant can't get out of its 'death grip' and dies in that position. This manipulated biting is not part of the regular behavior of a healthy ant. It is a novel behavior induced by the fungus - an *extended phenotype* of the parasite. The parasite then uses the ant’s tissues as a carbon source to grow a stalk from between the ant’s thorax and head, followed by a fruiting body containing infective ascospores for next round of infections.

I am currently doing field and lab studies on the Florida Carpenter ants to quantify their activity budget for foraging before and after fungal infections. I also want to understand how the fungus overrides the biological clocks of these nocturnal ants to make them undergo the characteristic biting behavior in the day-time.

---------------------------------------

Things that I intend to add here:

1. Current projects
1. Past research 
1. Cricket in Orlando
1. Academic resources 
1. Others
